/*
*proyecto Programado uno
*Kidiwn Jara Tracy y Niklas Herrmann Kay Thomas
*
 */
package Ventana;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSPanelsSlider;
import java.util.ArrayList;

/**
 *
 * @author Kidiwn Jara Tracy y Niklas Herrmann Kay Thomas
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.taclaempleados.setModel(modelo);
        this.modelo.addColumn("Nombre");
        this.modelo.addColumn("Apellidos");
        this.modelo.addColumn("Tipo_ID");
        this.modelo.addColumn("ID");
        this.modelo.addColumn("F_Nacimiento");
        this.modelo.addColumn("F_Contrato");
        this.modelo.addColumn("Rol");
        this.modelo.addColumn("Telefono");
        this.modelo.addColumn("Email");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //Codigo para la tabla
            
    DefaultTableModel modelo= new DefaultTableModel();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bbn8 = new rojerusan.RSButtonIconI();
        bbn1 = new rojerusan.RSButtonIconI();
        bbn2 = new rojerusan.RSButtonIconI();
        bbn3 = new rojerusan.RSButtonIconI();
        bbn4 = new rojerusan.RSButtonIconI();
        bbn5 = new rojerusan.RSButtonIconI();
        bbn6 = new rojerusan.RSButtonIconI();
        bbn7 = new rojerusan.RSButtonIconI();
        jLabel9 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pln1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        marcas = new javax.swing.JTextPane();
        OP_Marcas = new javax.swing.JComboBox<>();
        BnMarcas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pln2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Lista_mostrar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        nasientos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Npuertas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        combustible = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        transmicion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pln3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taclaempleados = new javax.swing.JTable();
        nombre1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidos1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipo_id = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        id1 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Contrato = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        rol = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        registrar1 = new javax.swing.JButton();
        pln4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        idc = new javax.swing.JTextField();
        nomc = new javax.swing.JTextField();
        apec = new javax.swing.JTextField();
        fc = new javax.swing.JTextField();
        telc = new javax.swing.JTextField();
        mailc = new javax.swing.JTextField();
        acepc = new rojerusan.RSButtonIconI();
        CC = new javax.swing.JTextField();
        PC = new javax.swing.JTextField();
        tipoc = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        pln5 = new javax.swing.JPanel();
        clientname = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        marcaCliente = new javax.swing.JTextField();
        modeloclient = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        registrar = new rojerusan.RSButtonIconI();
        jLabel5 = new javax.swing.JLabel();
        pln6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pln7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pln8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bbn8.setBackground(new java.awt.Color(236, 6, 8));
        bbn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/layers.png"))); // NOI18N
        bbn8.setText("Detalles del servicio");
        bbn8.setColorHover(new java.awt.Color(126, 234, 230));
        bbn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn8ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 240, 30));

        bbn1.setBackground(new java.awt.Color(236, 6, 8));
        bbn1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(206, 0, 0)));
        bbn1.setForeground(new java.awt.Color(197, 1, 20));
        bbn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/settings.png"))); // NOI18N
        bbn1.setText("Registro de marcas");
        bbn1.setColorHover(new java.awt.Color(236, 4, 5));
        bbn1.setFocusCycleRoot(true);
        bbn1.setSelected(true);
        bbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn1ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 30));

        bbn2.setBackground(new java.awt.Color(236, 6, 8));
        bbn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/settings.png"))); // NOI18N
        bbn2.setText("Registro de modelos");
        bbn2.setColorHover(new java.awt.Color(57, 172, 1));
        bbn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn2ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 30));

        bbn3.setBackground(new java.awt.Color(236, 6, 8));
        bbn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/list.png"))); // NOI18N
        bbn3.setText("Registro de empleados");
        bbn3.setColorHover(new java.awt.Color(255, 250, 0));
        bbn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn3ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 30));

        bbn4.setBackground(new java.awt.Color(236, 6, 8));
        bbn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user-1.png"))); // NOI18N
        bbn4.setText("Registro de clientes");
        bbn4.setColorHover(new java.awt.Color(254, 99, 75));
        bbn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn4ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 30));

        bbn5.setBackground(new java.awt.Color(236, 6, 8));
        bbn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/document.png"))); // NOI18N
        bbn5.setText("Registro de Vehiculos");
        bbn5.setColorHover(new java.awt.Color(1, 1, 1));
        bbn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn5ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        bbn6.setBackground(new java.awt.Color(236, 6, 8));
        bbn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servi.png"))); // NOI18N
        bbn6.setText("Servicios del taller");
        bbn6.setColorHover(new java.awt.Color(172, 104, 2));
        bbn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn6ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 30));

        bbn7.setBackground(new java.awt.Color(236, 6, 8));
        bbn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/layers.png"))); // NOI18N
        bbn7.setText("Historial de los pedidos");
        bbn7.setColorHover(new java.awt.Color(209, 67, 156));
        bbn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbn7ActionPerformed(evt);
            }
        });
        jPanel1.add(bbn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPeque.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, -1));

        rSPanelsSlider1.setBackground(new java.awt.Color(254, 254, 254));

        pln1.setBackground(new java.awt.Color(254, 254, 254));
        pln1.setName("pln1"); // NOI18N
        pln1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Waree", 2, 18)); // NOI18N
        jLabel10.setText("Ingrese La Marca");
        pln1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 50));

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(marcas);

        pln1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        OP_Marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incluir", "Eliminar" }));
        OP_Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_MarcasActionPerformed(evt);
            }
        });
        pln1.add(OP_Marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        BnMarcas.setBackground(new java.awt.Color(254, 254, 254));
        BnMarcas.setForeground(new java.awt.Color(254, 254, 254));
        BnMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok.png"))); // NOI18N
        BnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnMarcasActionPerformed(evt);
            }
        });
        pln1.add(BnMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        jLabel1.setText("Pantalla#1");
        pln1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 664, 444));

        rSPanelsSlider1.add(pln1, "card2");

        pln2.setBackground(new java.awt.Color(254, 254, 254));
        pln2.setName("pln2"); // NOI18N
        pln2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel11.setText("Ingrese la descripción ");
        pln2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 40));

        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        pln2.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, -1));

        jLabel12.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel12.setText("Seleccione una marca de vehículo");
        pln2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Lista_mostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auto1", "auto2", "auto3" }));
        Lista_mostrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Lista_mostrarItemStateChanged(evt);
            }
        });
        Lista_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_mostrarActionPerformed(evt);
            }
        });
        pln2.add(Lista_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, -1));

        jLabel13.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel13.setText("Cantidad de asientos");
        pln2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 30));
        pln2.add(nasientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 30));

        jLabel14.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel14.setText("Cantidad de Puertas");
        pln2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 40));
        pln2.add(Npuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 30));

        jLabel15.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel15.setText("Compustible");
        pln2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        pln2.add(combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, -1));

        jLabel16.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel16.setText("Transmisión");
        pln2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
        pln2.add(transmicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        jLabel2.setText("Pantalla#2");
        pln2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 664, 444));

        rSPanelsSlider1.add(pln2, "card3");

        pln3.setBackground(new java.awt.Color(254, 254, 254));
        pln3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pln3.setForeground(new java.awt.Color(254, 254, 254));
        pln3.setName("pln3"); // NOI18N
        pln3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taclaempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(taclaempleados);

        pln3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, 750, 119));
        pln3.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, -1));

        jLabel3.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel3.setText("Rigistro de Empleados");
        pln3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 12, 176, 34));
        pln3.add(apellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, -1));

        jLabel18.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel18.setText("Apellidos");
        pln3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel17.setText("Nombre");
        pln3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, 70, -1));

        tipo_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Pasaporte" }));
        pln3.add(tipo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));

        jLabel19.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel19.setText("Tipo de Identificación");
        pln3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        pln3.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 150, -1));

        jLabel20.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel20.setText("Identificación");
        pln3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        pln3.add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 130, -1));

        jLabel21.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel21.setText("Fecha de Nacimiento");
        pln3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel22.setText("Fecha de Contrato");
        pln3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));
        pln3.add(Contrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 170, -1));

        jLabel23.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel23.setText("Rol");
        pln3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 30, -1));
        pln3.add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 160, -1));

        jLabel24.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel24.setText("Teléfono");
        pln3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));
        pln3.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 140, -1));
        pln3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 190, -1));

        jLabel25.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel25.setText("Email");
        pln3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        registrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok.png"))); // NOI18N
        registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar1ActionPerformed(evt);
            }
        });
        pln3.add(registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 50, 20));

        rSPanelsSlider1.add(pln3, "card4");

        pln4.setBackground(new java.awt.Color(254, 254, 254));
        pln4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pln4.setName("pln4"); // NOI18N
        pln4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(1, 1, 1));
        jLabel26.setText("Nombre");
        pln4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 30));

        jLabel27.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel27.setText("Apellidos");
        pln4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel28.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel28.setText("Tipo de Identificación");
        pln4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel29.setText("Identificación");
        pln4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel31.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel31.setText("Fecha de Nacimiento");
        pln4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        pln4.add(idc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, -1));
        pln4.add(nomc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));
        pln4.add(apec, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));
        pln4.add(fc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, -1));
        pln4.add(telc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 150, -1));
        pln4.add(mailc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 150, -1));

        acepc.setBackground(new java.awt.Color(254, 254, 254));
        acepc.setForeground(new java.awt.Color(5, 0, 0));
        acepc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrer.png"))); // NOI18N
        acepc.setText("            Regístrar");
        acepc.setColorHover(new java.awt.Color(71, 156, 1));
        acepc.setColorText(new java.awt.Color(1, 1, 1));
        acepc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        acepc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acepcActionPerformed(evt);
            }
        });
        pln4.add(acepc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 150, -1));
        pln4.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, -1));
        pln4.add(PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 150, -1));

        tipoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Pasaporte" }));
        pln4.add(tipoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, -1));

        jLabel30.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel30.setText("Email");
        pln4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        pln4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 660, 400));

        jLabel32.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel32.setText("Provincia");
        pln4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel33.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel33.setText("Cantón");
        pln4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel34.setText("Teléfono");
        pln4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        rSPanelsSlider1.add(pln4, "card5");

        pln5.setBackground(new java.awt.Color(254, 254, 254));
        pln5.setName("pln5"); // NOI18N
        pln5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pln5.add(clientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 220, -1));

        jLabel35.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel35.setText("Placa del Vehículo");
        pln5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });
        pln5.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 230, -1));

        jLabel36.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel36.setText("Nombre del Cliente");
        pln5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel37.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel37.setText("Marca del Vehículo");
        pln5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel38.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel38.setText("Modelo del Vehículo");
        pln5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel39.setFont(new java.awt.Font("Yrsa Light", 2, 18)); // NOI18N
        jLabel39.setText("Año del Vehículo");
        pln5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        marcaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaClienteActionPerformed(evt);
            }
        });
        pln5.add(marcaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 230, -1));

        modeloclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloclientActionPerformed(evt);
            }
        });
        pln5.add(modeloclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 230, -1));

        año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoActionPerformed(evt);
            }
        });
        pln5.add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 230, -1));

        registrar.setBackground(new java.awt.Color(254, 254, 254));
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/document.png"))); // NOI18N
        registrar.setText("             Regístrar");
        registrar.setColorText(new java.awt.Color(1, 1, 1));
        registrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pln5.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 180, -1));

        jLabel5.setBackground(new java.awt.Color(254, 254, 254));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        pln5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 650, 400));

        rSPanelsSlider1.add(pln5, "card6");

        pln6.setName("pln6"); // NOI18N

        jLabel6.setText("Pantalla#6");

        javax.swing.GroupLayout pln6Layout = new javax.swing.GroupLayout(pln6);
        pln6.setLayout(pln6Layout);
        pln6Layout.setHorizontalGroup(
            pln6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pln6Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );
        pln6Layout.setVerticalGroup(
            pln6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pln6Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pln6, "card7");

        pln7.setName("pln7"); // NOI18N

        jLabel7.setText("Pantalla#7");

        javax.swing.GroupLayout pln7Layout = new javax.swing.GroupLayout(pln7);
        pln7.setLayout(pln7Layout);
        pln7Layout.setHorizontalGroup(
            pln7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pln7Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );
        pln7Layout.setVerticalGroup(
            pln7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pln7Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pln7, "card8");

        pln8.setName("pln8"); // NOI18N

        jLabel8.setText("Pantalla#8");

        javax.swing.GroupLayout pln8Layout = new javax.swing.GroupLayout(pln8);
        pln8.setLayout(pln8Layout);
        pln8Layout.setHorizontalGroup(
            pln8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pln8Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );
        pln8Layout.setVerticalGroup(
            pln8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pln8Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pln8, "card9");

        rSButtonIconI1.setBackground(new java.awt.Color(236, 6, 8));
        rSButtonIconI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        rSButtonIconI1.setText("Salir");
        rSButtonIconI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn1ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn1.isSelected()){
            this.bbn1.setSelected(true);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln1, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn1ActionPerformed

    private void bbn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn2ActionPerformed
        // TODO add your handling code here:
         if(!this.bbn2.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(true);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln2, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn2ActionPerformed

    private void bbn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn3ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn3.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(true);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln3, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn3ActionPerformed

    private void bbn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn4ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn4.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(true);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln4, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn4ActionPerformed

    private void bbn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn5ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn5.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(true);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln5, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn5ActionPerformed

    private void bbn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn6ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn6.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(true);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln6, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn6ActionPerformed

    private void bbn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn7ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn7.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(true);
            this.bbn8.setSelected(false);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln7, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn7ActionPerformed

    private void bbn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbn8ActionPerformed
        // TODO add your handling code here:
        if(!this.bbn8.isSelected()){
            this.bbn1.setSelected(false);
            this.bbn2.setSelected(false);
            this.bbn3.setSelected(false);
            this.bbn4.setSelected(false);
            this.bbn5.setSelected(false);
            this.bbn6.setSelected(false);
            this.bbn7.setSelected(false);
            this.bbn8.setSelected(true);
            //pln1
            rSPanelsSlider1.setPanelSlider(pln8, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_bbn8ActionPerformed

    private void rSButtonIconI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButtonIconI1ActionPerformed

    private void OP_MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_MarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_MarcasActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar1ActionPerformed
        /**
         * Ingresa Los datos en Pantalla y los Almacena en las Variables de la Clase
         * Evalua si algun espacio esta en blanco para que no pueda ingrsar nada si el espacio esta en blancoa
         */
        if(nombre1.getText().equals("") || apellidos1.getText().equals("")
                || id1.getText().equals("") || Fecha1.getText().equals("")
                || Contrato.getText().equals("") || rol.getText().equals("")
                || tel.getText().equals("") || email.getText().equals("")){
            
            JOptionPane.showMessageDialog(null,"Espacio Vacio \n Debe de llenar Todas los datos",null,
                                    JOptionPane.ERROR_MESSAGE);
            nombre1.setFocusable(true);
            
        }else{
        this.modelo.addRow(new Object [] {this.nombre1.getText(),this.apellidos1.getText(),
            this.tipo_id.getSelectedItem(),this.id1.getText(),this.Fecha1.getText(),
                this.Contrato.getText(),this.rol.getText(),this.tel.getText(),this.email.getText()});
        this.nombre1.setText("");
        this.apellidos1.setText("");
        this.tipo_id.setSelectedIndex(0);
        this.id1.setText("");
        this.Fecha1.setText("");
        this.Contrato.setText("");
        this.rol.setText("");
        this.tel.setText("");
        this.email.setText("");
        nombre1.grabFocus();
                    }
    }//GEN-LAST:event_registrar1ActionPerformed

    private void acepcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acepcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acepcActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed

    private void marcaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaClienteActionPerformed

    private void modeloclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloclientActionPerformed

    private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoActionPerformed

    private void BnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnMarcasActionPerformed
   ArrayList tempo = new ArrayList();
    if(OP_Marcas.getSelectedItem().equals("Incluir")){
       tempo.add(marcas.getText());
        Marcas_All tm = new Marcas_All();
        
        tm.agregalista(tempo);
        JOptionPane.showMessageDialog(null,"Marca Agregada con Exito ala base de datos");
        marcas.setText("");
        
         
    }
    }//GEN-LAST:event_BnMarcasActionPerformed

    private void Lista_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_mostrarActionPerformed
        
    }//GEN-LAST:event_Lista_mostrarActionPerformed

    private void Lista_mostrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Lista_mostrarItemStateChanged
        // TODO add your handling code here:
       
        Marcas_All tm = new Marcas_All();
        
        //Lista_mostrar.add();
    }//GEN-LAST:event_Lista_mostrarItemStateChanged
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnMarcas;
    private javax.swing.JTextField CC;
    private javax.swing.JTextField Contrato;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JComboBox<String> Lista_mostrar;
    private javax.swing.JTextField Npuertas;
    private javax.swing.JComboBox<String> OP_Marcas;
    private javax.swing.JTextField PC;
    private rojerusan.RSButtonIconI acepc;
    private javax.swing.JTextField apec;
    private javax.swing.JTextField apellidos1;
    private javax.swing.JTextField año;
    private rojerusan.RSButtonIconI bbn1;
    private rojerusan.RSButtonIconI bbn2;
    private rojerusan.RSButtonIconI bbn3;
    private rojerusan.RSButtonIconI bbn4;
    private rojerusan.RSButtonIconI bbn5;
    private rojerusan.RSButtonIconI bbn6;
    private rojerusan.RSButtonIconI bbn7;
    private rojerusan.RSButtonIconI bbn8;
    private javax.swing.JComboBox<String> clientname;
    private javax.swing.JTextField combustible;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fc;
    private javax.swing.JFormattedTextField id1;
    private javax.swing.JTextField idc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mailc;
    private javax.swing.JTextField marcaCliente;
    private javax.swing.JTextPane marcas;
    private javax.swing.JTextField modeloclient;
    private javax.swing.JTextField nasientos;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nomc;
    private javax.swing.JTextField placa;
    private javax.swing.JPanel pln1;
    private javax.swing.JPanel pln2;
    private javax.swing.JPanel pln3;
    private javax.swing.JPanel pln4;
    private javax.swing.JPanel pln5;
    private javax.swing.JPanel pln6;
    private javax.swing.JPanel pln7;
    private javax.swing.JPanel pln8;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSButtonIconI registrar;
    private javax.swing.JButton registrar1;
    private javax.swing.JTextField rol;
    private javax.swing.JTable taclaempleados;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField telc;
    private javax.swing.JComboBox<String> tipo_id;
    private javax.swing.JComboBox<String> tipoc;
    private javax.swing.JTextField transmicion;
    // End of variables declaration//GEN-END:variables
}
